Completed react-function-components exercise. - Plasencia Alex
a-plasencia/c0122-code-solutions pull request #108
Opened 2022-03-29 22:37 UTC by a-plasencia

![Screen Shot 2022-03-29 at 3 33 00 PM](https://user-images.githubusercontent.com/36422433/160718152-52507186-b8d9-43d2-b240-2e8ab7e816c2.png)

2022-03-29 23:41 UTC, thebearingedge requested changes

2022-03-29 23:41 UTC, thebearingedge commented on react-function-components/src/index.jsx
> +  CustomButton(),
Create a react element instead of calling your function here.

2022-03-30 00:55 UTC, a-plasencia reviewed
![Screen Shot 2022-03-29 at 5 53 18 PM](https://user-images.githubusercontent.com/36422433/160729764-b36ec238-4b6b-49e4-9bd2-04488c1d13f4.png)

2022-03-30 16:37 UTC, thebearingedge approved these changes

2022-03-30 17:08 UTC, merged