Completed array-manipulation-1 exercise. - Alex Plasencia
a-plasencia/c0122-code-solutions pull request #37
Opened 2022-02-07 02:58 UTC by a-plasencia

![Screen Shot 2022-02-06 at 6 58 29 PM](https://user-images.githubusercontent.com/36422433/152717620-d16ea393-6180-4b4c-a3a8-11a72de7dcd4.png)

2022-02-07 20:37 UTC, codingcodymiller requested changes

2022-02-07 20:37 UTC, codingcodymiller commented on array-manipulation-1/src/initial.js
> +    if (i !== lastItem) {
If you stop the loop one index sooner, you won't need this conditional 🤓

2022-02-07 20:37 UTC, codingcodymiller commented on array-manipulation-1/src/tail.js
> +    if (i !== 0) {
Same here, if you start the loop at `1`, you won't need a conditional

2022-02-09 05:40 UTC, a-plasencia reviewed
![Screen Shot 2022-02-08 at 9 39 59 PM](https://user-images.githubusercontent.com/36422433/153128858-a058e17a-9aa2-4742-98a5-51670e18da56.png)

2022-02-09 16:01 UTC, thebearingedge approved these changes

2022-02-09 18:10 UTC, merged